---
- hosts: spark-master*
  gather_facts: no
  become: yes
  ignore_errors: True
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes
    - name: Check if a reboot is needed for Debian and Ubuntu boxes
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no
      ###Install prerequites
    - name: Install prerequites
      apt:
        name: ['freetds-bin', 'krb5-user', 'ldap-utils', 'libffi7', 'libsasl2-2', 'libsasl2-modules', 'libssl1.1', 'locales ', 'lsb-release', 'sasl2-bin', 'sqlite3', 'unixodbc', 'build-essential', 'postgresql-client']
        install_recommends: no
        state: present
    - name: Install airflow
      pip:
        name:
          - apache-airflow==1.10.12
          - testresources
        extra_args: "--constraint \"https://raw.githubusercontent.com/apache/airflow/constraints-1.10.12/constraints-3.7.txt\""
    - name: Install airflow extra
      pip:
        name:
          - apache-airflow[postgres,gcp]==1.10.12
        extra_args: "--constraint \"https://raw.githubusercontent.com/apache/airflow/constraints-1.10.12/constraints-3.7.txt\""
