version: '2.1'
networks:
   status_net:
      driver: bridge
services:
  prometheus:
    hostname: PROMETHEUS
    domainname: dtrace.net
    image: prom/prometheus
    volumes:
      - /opt/www/status.dtrace.net/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - status_net
        #ports:
        #- '9900:9090'
  postgis-node:
    hostname: postgis
    domainname: dtrace.net
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    networks:
      - status_net
  postgis-exporter:
    container_name: postgis-exporter
    hostname: postgis
    domainname: dtrace.net
    image: wrouesnel/postgres_exporter
    restart: always
    environment:
      DATA_SOURCE_NAME: "postgresql://DBUSER:DBPWD@localhost:5432/postgres?sslmode=disable"
      PG_EXPORTER_WEB_LISTEN_ADDRESS: ":9911"
    network_mode: "host"
  grafana:
    hostname: Grafana
    domainname: dtrace.net
    image: grafana/grafana
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=insightDE20C
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    networks:
      - status_net
volumes:
   prometheus:
   grafana:
