---
- hosts: aws
  gather_facts: no
  become: yes
  ignore_errors: True
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull node exporter image
      shell: "docker pull prom/node-exporter"
    - name: Add user to docker group
      shell: "usermod -aG docker AWSUSER"
- hosts: postgis*
  gather_facts: no
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull postgres exporter image
      shell: "docker pull wrouesnel/postgres_exporter; docker pull grafana/grafana; docker pull prom/prometheus"
