global:
    scrape_interval: 5s
    external_labels:
        monitor: 'status.dtrace.net'
scrape_configs:
    - job_name: 'Nodes'
      scrape_interval: 10s
      static_configs:
        - targets:
          - '10.0.0.8:9910'
          - '10.0.0.7:9910'
          - '10.0.0.13:9910'
          - '10.0.0.10:9910'
          - 'postgis-node:9100'
    - job_name: 'Spark'
      scrape_interval: 30s
      metrics_path: /metrics
      honor_labels: true
      static_configs:
        - targets: ["10.0.0.8:9911"]
    - job_name: 'postgis'
      scrape_interval: 30s
      metrics_path: /metrics
      honor_labels: true
      static_configs:
        - targets: ["10.0.0.9:9911"]
