---
- hosts: spark-master*
  gather_facts: no
  ignore_errors: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Start Spark Cluster
      shell: "/opt/spark/sbin/start-all.sh"
