CREATE OR REPLACE PROCEDURE FIND_EMPTY_REC()
LANGUAGE plpgsql
AS $$
DECLARE
	REC RECORD;
	tmpREC RECORD;
	CUR CURSOR FOR SELECT ID FROM TRIPDATA_FILENAME WHERE ISLOCKED=1;
	TMPCUR REFCURSOR;
BEGIN
	OPEN CUR;
	LOOP
		FETCH CUR INTO REC;
		EXIT WHEN NOT FOUND;
		RAISE NOTICE 'CHECKING %',REC.ID;

		OPEN TMPCUR FOR SELECT COUNT(ID) AS TRIPCOUNT FROM TRIPDATA WHERE SOURCEID=REC.ID;
			FETCH TMPCUR INTO TMPREC;
		CLOSE TMPCUR;
		IF TMPREC.TRIPCOUNT < 1000 THEN
			/*
        		OPEN TMPCUR FOR SELECT COUNT(ID) AS TRIPCOUNT FROM TRIPDATA_GEO WHERE SOURCEID=REC.ID;
        			FETCH TMPCUR INTO TMPREC;
        		CLOSE TMPCUR;
			IF TMPREC.TRIPCOUNT < 1000 THEN
				BEGIN
					UPDATE TRIPDATA_FILENAME SET ISLOCKED=0 WHERE ID=REC.ID;
				END;
				RAISE NOTICE 'NO RECORD FOR %',REC.ID;
			ELSE
				BEGIN
					UPDATE TRIPDATA_FILENAME SET ISLOCKED=2 WHERE ID=REC.ID;
				END;
			END IF;
*/
			BEGIN
				UPDATE TRIPDATA_FILENAME SET ISLOCKED=0 WHERE ID=REC.ID;
			END;
			RAISE NOTICE '---------------------';
			RAISE NOTICE 'NO RECORD FOR %',REC.ID;
		ELSE
			BEGIN
				UPDATE TRIPDATA_FILENAME SET ISLOCKED=2 WHERE ID=REC.ID;
			END;
		END IF;
	END LOOP;
	CLOSE CUR;
END; $$
