CREATE OR REPLACE PROCEDURE FIND_GOOD_REC()
LANGUAGE plpgsql
AS $$
DECLARE
	tmpREC RECORD;
	TMPCUR REFCURSOR;
	I_PRE INTEGER;
	I_POST INTEGER;
	
BEGIN
	SELECT last_value INTO I_PRE FROM TRIPDATA_ID_SEQ;
	SELECT last_value INTO I_POST FROM TRIPDATA_ID_SEQ;
	LOOP
		I_PRE := I_PRE-10000;
		OPEN TMPCUR FOR SELECT SOURCEID, COUNT(ID) AS ID_COUNT FROM TRIPDATA WHERE ID >= I_PRE AND ID<= I_POST AND SOURCEID IN (
			SELECT ID FROM TRIPDATA_FILENAME_NEW WHERE ISLOCKED=1
		)
		GROUP BY SOURCEID
		ORDER BY ID_COUNT DESC
		LIMIT 1;
			FETCH TMPCUR INTO TMPREC;
		CLOSE TMPCUR;
		IF TMPREC.ID_COUNT>1000 THEN
			UPDATE TRIPDATA_FILENAME_NEW SET ISLOCKED=2 WHERE ID=TMPREC.SOURCEID;
			COMMIT;
			RAISE NOTICE '% IS GOOD',TMPREC.SOURCEID;
		END IF;
		IF I_POST < 10000 THEN
			EXIT;
		END IF;
		I_POST := I_POST-10000;
	END LOOP;
END; $$
